# Generating Experimental Datasets
AirBnB Price Prediction

In [3]:
import pandas as pd
import matplotlib as plt
import numpy as np
from scipy import stats
from matplotlib import pyplot

pd.set_option('display.max_columns', None)

In [25]:
df = pd.read_csv("../sample_data_6.2.csv")
print(df.shape)
df.head()

(24451, 58)

,log_price,host_listings_count,host_total_listings_count,neighbourhood_cleansed,zipcode,property_type,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,latitude,longitude,number_of_reviews,number_of_reviews_ltm,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,private,shared,flexible,moderate,summary_SVD1,summary_SVD2,summary_SVD3,space_SVD1,space_SVD2,space_SVD3,description_SVD1,description_SVD2,description_SVD3,neighborhood_overview_SVD1,neighborhood_overview_SVD2,neighborhood_overview_SVD3,access_SVD1,access_SVD2,access_SVD3,interaction_SVD1,interaction_SVD2,interaction_SVD3,house_rules_SVD1,house_rules_SVD2,house_rules_SVD3,host_about_SVD1,host_about_SVD2,host_about_SVD3
0,6.493754,1.0,1.0,58,62,21,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,1,0,0,0,0,0,2663.663320,-33.94739,18.47600,49,7,0,0,0.610000,0,0,0,1,-3.617314e-02,2.243312e-02,-4.086990e-02,0.001492,-0.124890,0.038315,0.010927,-0.146725,-0.096208,-0.010653,-0.003074,-0.102751,-0.038241,-0.165265,0.139044,0.010833,-0.010946,-0.003911,0.150103,-0.020829,0.094639,-1.661607e-01,-1.274255e-02,-4.633390e-02
1,7.652071,5.0,5.0,17,125,3,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,0,0,0,1,0,0,1459.786779,-33.90771,18.40535,2,0,0,0,0.020000,0,0,0,0,-5.004628e-02,-3.579589e-02,3.588734e-02,0.022125,0.019245,0.034231,0.005448,-0.021422,-0.029890,0.089120,-0.004582,0.040303,-0.082266,-0.157155,0.064531,0.008448,-0.048546,-0.077724,-0.021170,-0.010612,0.142739,1.258846e-01,1.352890e-02,3.054207e-02
2,7.624619,12.0,12.0,30,31,25,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,1,0,0,1,0,0,3612.146587,-33.80114,18.46180,27,2,0,0,0.370000,0,0,0,0,6.196324e-02,6.545631e-03,-1.251741e-01,0.058922,-0.003018,-0.087462,-0.051035,0.063836,-0.106632,0.056761,0.018276,0.027745,0.090246,-0.084449,0.026858,-0.062756,-0.004105,0.048072,-0.002762,0.029302,0.165877,-4.881418e-02,2.009630e-03,3.447136e-02
3,7.198184,5.0,5.0,41,31,1,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,0,0,0,1,0,0,3260.343187,-33.85878,18.48970,5,0,4,0,0.060000,1,0,0,0,-1.029555e-01,-5.844210e-02,3.283490e-02,0.028287,0.112263,-0.031700,-0.006912,-0.017670,-0.009801,-0.081795,-0.042419,-0.101334,0.018954,-0.039953,0.004325,-0.085090,-0.053575,0.009867,-0.036506,-0.018924,-0.245281,1.268197e-01,-8.067963e-02,3.203286e-03
4,6.329721,1.0,1.0,86,16,1,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,1,0,0,1,0,0,512.116431,-34.11124,18.82349,0,0,0,0,0.919543,0,0,0,0,-2.054624e-16,-8.809054e-17,2.373795e-15,-0.051308,-0.073710,-0.068863,0.102251,-0.046986,0.035174,0.016118,0.041624,-0.007335,-0.063371,0.012052,0.032089,-0.092871,0.015986,0.066478,0.078126,-0.018296,0.068100,-4.288458e-17,-9.670931e-16,-1.121728e-15

## Experiment 1.1 - Continuous features

In [10]:
df_continuous = df[["log_price", "host_listings_count","accommodates","bathrooms","bedrooms","beds","security_deposit","cleaning_fee","guests_included", "maximum_minimum_nights", "review_scores_rating", "review_scores_location", "latitude","longitude","number_of_reviews","number_of_reviews_ltm","calculated_host_listings_count_private_rooms","calculated_host_listings_count_shared_rooms","reviews_per_month"]]
print(df_continuous.shape[1])
df_continuous.head()

19

,log_price,host_listings_count,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,latitude,longitude,number_of_reviews,number_of_reviews_ltm,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6.493754,1.0,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,-33.94739,18.47600,49,7,0,0,0.610000
1,7.652071,5.0,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,-33.90771,18.40535,2,0,0,0,0.020000
2,7.624619,12.0,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,-33.80114,18.46180,27,2,0,0,0.370000
3,7.198184,5.0,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,-33.85878,18.48970,5,0,4,0,0.060000
4,6.329721,1.0,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,-34.11124,18.82349,0,0,0,0,0.919543

## Experiment 1.2 - Categorical features

In [11]:
df_cat= df[["log_price", "neighbourhood_cleansed", "zipcode", "property_type", "entire","luxury_moderate","luxury_super_strict_95","strict_14_with_grace_period","super_strict_30","super_strict_60","amenity_scores", "private","shared","flexible","moderate",]]
print(df_cat.shape[1])
df_cat.head()

15

,log_price,neighbourhood_cleansed,zipcode,property_type,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,private,shared,flexible,moderate
0,6.493754,58,62,21,1,0,0,0,0,0,2663.663320,0,0,0,1
1,7.652071,17,125,3,0,0,0,1,0,0,1459.786779,0,0,0,0
2,7.624619,30,31,25,1,0,0,1,0,0,3612.146587,0,0,0,0
3,7.198184,41,31,1,0,0,0,1,0,0,3260.343187,1,0,0,0
4,6.329721,86,16,1,1,0,0,1,0,0,512.116431,0,0,0,0

## Experiment 1.3 - Textual features

In [12]:
df_text= df[["log_price", "summary_SVD1", "summary_SVD2", "summary_SVD3", "space_SVD1", "space_SVD2", "space_SVD3", "description_SVD1", "description_SVD2", "description_SVD3", "neighborhood_overview_SVD1", "neighborhood_overview_SVD2", "neighborhood_overview_SVD3", "access_SVD1","access_SVD2","access_SVD3","interaction_SVD1","interaction_SVD2","interaction_SVD3", "house_rules_SVD1","house_rules_SVD2","house_rules_SVD3","host_about_SVD1","host_about_SVD2","host_about_SVD3"]]
print(df_text.shape[1])
df_text.head()

25

,log_price,summary_SVD1,summary_SVD2,summary_SVD3,space_SVD1,space_SVD2,space_SVD3,description_SVD1,description_SVD2,description_SVD3,neighborhood_overview_SVD1,neighborhood_overview_SVD2,neighborhood_overview_SVD3,access_SVD1,access_SVD2,access_SVD3,interaction_SVD1,interaction_SVD2,interaction_SVD3,house_rules_SVD1,house_rules_SVD2,house_rules_SVD3,host_about_SVD1,host_about_SVD2,host_about_SVD3
0,6.493754,-3.617314e-02,2.243312e-02,-4.086990e-02,0.001492,-0.124890,0.038315,0.010927,-0.146725,-0.096208,-0.010653,-0.003074,-0.102751,-0.038241,-0.165265,0.139044,0.010833,-0.010946,-0.003911,0.150103,-0.020829,0.094639,-1.661607e-01,-1.274255e-02,-4.633390e-02
1,7.652071,-5.004628e-02,-3.579589e-02,3.588734e-02,0.022125,0.019245,0.034231,0.005448,-0.021422,-0.029890,0.089120,-0.004582,0.040303,-0.082266,-0.157155,0.064531,0.008448,-0.048546,-0.077724,-0.021170,-0.010612,0.142739,1.258846e-01,1.352890e-02,3.054207e-02
2,7.624619,6.196324e-02,6.545631e-03,-1.251741e-01,0.058922,-0.003018,-0.087462,-0.051035,0.063836,-0.106632,0.056761,0.018276,0.027745,0.090246,-0.084449,0.026858,-0.062756,-0.004105,0.048072,-0.002762,0.029302,0.165877,-4.881418e-02,2.009630e-03,3.447136e-02
3,7.198184,-1.029555e-01,-5.844210e-02,3.283490e-02,0.028287,0.112263,-0.031700,-0.006912,-0.017670,-0.009801,-0.081795,-0.042419,-0.101334,0.018954,-0.039953,0.004325,-0.085090,-0.053575,0.009867,-0.036506,-0.018924,-0.245281,1.268197e-01,-8.067963e-02,3.203286e-03
4,6.329721,-2.054624e-16,-8.809054e-17,2.373795e-15,-0.051308,-0.073710,-0.068863,0.102251,-0.046986,0.035174,0.016118,0.041624,-0.007335,-0.063371,0.012052,0.032089,-0.092871,0.015986,0.066478,0.078126,-0.018296,0.068100,-4.288458e-17,-9.670931e-16,-1.121728e-15

## Experiment 1.4 - Continuous + Categorical features

In [18]:
df_cont_cat = df[["log_price", "host_listings_count","accommodates","bathrooms","bedrooms","beds","security_deposit","cleaning_fee","guests_included", "maximum_minimum_nights", "review_scores_rating", "review_scores_location", "latitude","longitude","number_of_reviews","number_of_reviews_ltm","calculated_host_listings_count_private_rooms","calculated_host_listings_count_shared_rooms","reviews_per_month", "neighbourhood_cleansed", "zipcode", "property_type", "entire","luxury_moderate","luxury_super_strict_95","strict_14_with_grace_period","super_strict_30","super_strict_60","amenity_scores", "private","shared","flexible","moderate"]]
print(df_cont_cat.shape[1])
df_cont_cat.head()

33

,log_price,host_listings_count,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,latitude,longitude,number_of_reviews,number_of_reviews_ltm,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,neighbourhood_cleansed,zipcode,property_type,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,private,shared,flexible,moderate
0,6.493754,1.0,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,-33.94739,18.47600,49,7,0,0,0.610000,58,62,21,1,0,0,0,0,0,2663.663320,0,0,0,1
1,7.652071,5.0,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,-33.90771,18.40535,2,0,0,0,0.020000,17,125,3,0,0,0,1,0,0,1459.786779,0,0,0,0
2,7.624619,12.0,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,-33.80114,18.46180,27,2,0,0,0.370000,30,31,25,1,0,0,1,0,0,3612.146587,0,0,0,0
3,7.198184,5.0,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,-33.85878,18.48970,5,0,4,0,0.060000,41,31,1,0,0,0,1,0,0,3260.343187,1,0,0,0
4,6.329721,1.0,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,-34.11124,18.82349,0,0,0,0,0.919543,86,16,1,1,0,0,1,0,0,512.116431,0,0,0,0

## Experiment 1.5 - Continuous + Categorical + Textual features

In [20]:
df_cont_cat_text = df[["log_price", "host_listings_count","accommodates","bathrooms","bedrooms","beds","security_deposit","cleaning_fee","guests_included", "maximum_minimum_nights", "review_scores_rating", "review_scores_location", "latitude","longitude","number_of_reviews","number_of_reviews_ltm","calculated_host_listings_count_private_rooms","calculated_host_listings_count_shared_rooms","reviews_per_month", "neighbourhood_cleansed", "zipcode", "property_type", "entire","luxury_moderate","luxury_super_strict_95","strict_14_with_grace_period","super_strict_30","super_strict_60","amenity_scores", "private","shared","flexible","moderate", "summary_SVD1", "summary_SVD2", "summary_SVD3", "space_SVD1", "space_SVD2", "space_SVD3", "description_SVD1", "description_SVD2", "description_SVD3", "neighborhood_overview_SVD1", "neighborhood_overview_SVD2", "neighborhood_overview_SVD3", "access_SVD1","access_SVD2","access_SVD3","interaction_SVD1","interaction_SVD2","interaction_SVD3", "house_rules_SVD1","house_rules_SVD2","house_rules_SVD3","host_about_SVD1","host_about_SVD2","host_about_SVD3"]]
print(df_cont_cat_text.shape[1])
df_cont_cat_text.head()

57

,log_price,host_listings_count,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,latitude,longitude,number_of_reviews,number_of_reviews_ltm,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,neighbourhood_cleansed,zipcode,property_type,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,private,shared,flexible,moderate,summary_SVD1,summary_SVD2,summary_SVD3,space_SVD1,space_SVD2,space_SVD3,description_SVD1,description_SVD2,description_SVD3,neighborhood_overview_SVD1,neighborhood_overview_SVD2,neighborhood_overview_SVD3,access_SVD1,access_SVD2,access_SVD3,interaction_SVD1,interaction_SVD2,interaction_SVD3,house_rules_SVD1,house_rules_SVD2,house_rules_SVD3,host_about_SVD1,host_about_SVD2,host_about_SVD3
0,6.493754,1.0,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,-33.94739,18.47600,49,7,0,0,0.610000,58,62,21,1,0,0,0,0,0,2663.663320,0,0,0,1,-3.617314e-02,2.243312e-02,-4.086990e-02,0.001492,-0.124890,0.038315,0.010927,-0.146725,-0.096208,-0.010653,-0.003074,-0.102751,-0.038241,-0.165265,0.139044,0.010833,-0.010946,-0.003911,0.150103,-0.020829,0.094639,-1.661607e-01,-1.274255e-02,-4.633390e-02
1,7.652071,5.0,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,-33.90771,18.40535,2,0,0,0,0.020000,17,125,3,0,0,0,1,0,0,1459.786779,0,0,0,0,-5.004628e-02,-3.579589e-02,3.588734e-02,0.022125,0.019245,0.034231,0.005448,-0.021422,-0.029890,0.089120,-0.004582,0.040303,-0.082266,-0.157155,0.064531,0.008448,-0.048546,-0.077724,-0.021170,-0.010612,0.142739,1.258846e-01,1.352890e-02,3.054207e-02
2,7.624619,12.0,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,-33.80114,18.46180,27,2,0,0,0.370000,30,31,25,1,0,0,1,0,0,3612.146587,0,0,0,0,6.196324e-02,6.545631e-03,-1.251741e-01,0.058922,-0.003018,-0.087462,-0.051035,0.063836,-0.106632,0.056761,0.018276,0.027745,0.090246,-0.084449,0.026858,-0.062756,-0.004105,0.048072,-0.002762,0.029302,0.165877,-4.881418e-02,2.009630e-03,3.447136e-02
3,7.198184,5.0,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,-33.85878,18.48970,5,0,4,0,0.060000,41,31,1,0,0,0,1,0,0,3260.343187,1,0,0,0,-1.029555e-01,-5.844210e-02,3.283490e-02,0.028287,0.112263,-0.031700,-0.006912,-0.017670,-0.009801,-0.081795,-0.042419,-0.101334,0.018954,-0.039953,0.004325,-0.085090,-0.053575,0.009867,-0.036506,-0.018924,-0.245281,1.268197e-01,-8.067963e-02,3.203286e-03
4,6.329721,1.0,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,-34.11124,18.82349,0,0,0,0,0.919543,86,16,1,1,0,0,1,0,0,512.116431,0,0,0,0,-2.054624e-16,-8.809054e-17,2.373795e-15,-0.051308,-0.073710,-0.068863,0.102251,-0.046986,0.035174,0.016118,0.041624,-0.007335,-0.063371,0.012052,0.032089,-0.092871,0.015986,0.066478,0.078126,-0.018296,0.068100,-4.288458e-17,-9.670931e-16,-1.121728e-15

## Experiment 2.1 - Spatial features only

In [38]:
df2 = pd.read_csv("../5-Spatial Feature Eng - With Outliers - 2 Ward Features.csv")
df2 = df2.drop_duplicates("ward")
df2 = df2.drop(columns=["log_price"])
print(df2.shape)
df2.head(5)

(116, 7)

,ward,Low income,Middle-Low Income,Medium Income,High Income,Exceedingly High Income,listing_count
0,57.0,0,0,1,0,0,819.0
819,115.0,0,0,1,0,0,4307.0
5126,23.0,0,0,0,1,0,1330.0
6456,4.0,0,1,0,0,0,334.0
6790,83.0,0,1,0,0,0,271.0

In [43]:
df3 = pd.read_csv("../5-GIS Feature - With Outliers - Table Mountain_and_Beach_and_Ward.csv")
#df3 = pd.concat([df3, df["neighbourhood_cleansed"]], axis=1)
print(df3.shape)
df3.head()

(24451, 38)

,log_price,calculated_host_listings_count_entire_homes,host_identity_verified,instant_bookable,number_of_reviews_ltm,host_total_listings_count,zipcode,property_type,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,latitude,longitude,number_of_reviews,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,private,shared,flexible,moderate,table_mountain_dist,beach_dist,ward
0,6.493754,1,1.0,1,7,1.0,62,21,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,1,0,0,0,0,0,2663.663320,-33.94739,18.47600,49,0,0,0.610000,0,0,0,1,5992.238320,8846.454557,57.0
1,7.652071,0,0.0,1,0,5.0,125,3,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,0,0,0,1,0,0,1459.786779,-33.90771,18.40535,2,0,0,0.020000,0,0,0,0,4481.215598,1010.942474,115.0
2,7.624619,2,1.0,0,2,12.0,31,25,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,1,0,0,1,0,0,3612.146587,-33.80114,18.46180,27,0,0,0.370000,0,0,0,0,17212.514919,646.514699,23.0
3,7.198184,1,1.0,0,0,5.0,31,1,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,0,0,0,1,0,0,3260.343187,-33.85878,18.48970,5,4,0,0.060000,1,0,0,0,12759.126712,4387.900693,4.0
4,6.329721,1,0.0,0,0,1.0,16,1,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,1,0,0,1,0,0,512.116431,-34.11124,18.82349,0,0,0,0.919543,0,0,0,0,42818.200051,154.279498,83.0

In [46]:
df4 = pd.merge(df3, df2, how='left', left_on=['ward'], right_on=['ward'])
#df4.isnull().sum()
df4.head()

,log_price,calculated_host_listings_count_entire_homes,host_identity_verified,instant_bookable,number_of_reviews_ltm,host_total_listings_count,zipcode,property_type,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,latitude,longitude,number_of_reviews,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,private,shared,flexible,moderate,table_mountain_dist,beach_dist,ward,Low income,Middle-Low Income,Medium Income,High Income,Exceedingly High Income,listing_count
0,6.493754,1,1.0,1,7,1.0,62,21,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,1,0,0,0,0,0,2663.663320,-33.94739,18.47600,49,0,0,0.610000,0,0,0,1,5992.238320,8846.454557,57.0,0,0,1,0,0,819.0
1,7.652071,0,0.0,1,0,5.0,125,3,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,0,0,0,1,0,0,1459.786779,-33.90771,18.40535,2,0,0,0.020000,0,0,0,0,4481.215598,1010.942474,115.0,0,0,1,0,0,4307.0
2,7.624619,2,1.0,0,2,12.0,31,25,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,1,0,0,1,0,0,3612.146587,-33.80114,18.46180,27,0,0,0.370000,0,0,0,0,17212.514919,646.514699,23.0,0,0,0,1,0,1330.0
3,7.198184,1,1.0,0,0,5.0,31,1,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,0,0,0,1,0,0,3260.343187,-33.85878,18.48970,5,4,0,0.060000,1,0,0,0,12759.126712,4387.900693,4.0,0,1,0,0,0,334.0
4,6.329721,1,0.0,0,0,1.0,16,1,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,1,0,0,1,0,0,512.116431,-34.11124,18.82349,0,0,0,0.919543,0,0,0,0,42818.200051,154.279498,83.0,0,1,0,0,0,271.0

In [65]:
df2 = pd.read_csv("../5-Spatial data - Wine, Promonade.csv")
df2 = df2[["Promenade", "Wine"]]
df2 = pd.concat([df4, df2], axis=1)

df_spatial_only = df2[["log_price","ward","Low income","Middle-Low Income","Medium Income","High Income","Exceedingly High Income","listing_count","table_mountain_dist","beach_dist","Promenade","Wine"]]
df_spatial_only = pd.concat([df_spatial_only, df_cont_cat_text[["zipcode","latitude","longitude"]]], axis=1)
df_spatial_only.head()


#print(df_spatial_enh["log_price"].corr(df_spatial_enh["Low income"]))

,log_price,ward,Low income,Middle-Low Income,Medium Income,High Income,Exceedingly High Income,listing_count,table_mountain_dist,beach_dist,Promenade,Wine,zipcode,latitude,longitude
0,6.493754,57.0,0,0,1,0,0,819.0,5992.238320,8846.454557,8559.224147,0.0,62,-33.94739,18.47600
1,7.652071,115.0,0,0,1,0,0,4307.0,4481.215598,1010.942474,840.630176,1.0,125,-33.90771,18.40535
2,7.624619,23.0,0,0,0,1,0,1330.0,17212.514919,646.514699,12342.796409,0.0,31,-33.80114,18.46180
3,7.198184,4.0,0,1,0,0,0,334.0,12759.126712,4387.900693,9304.817930,0.0,31,-33.85878,18.48970
4,6.329721,83.0,0,1,0,0,0,271.0,42818.200051,154.279498,45338.822717,0.0,16,-34.11124,18.82349

## Experiment 2.2 - No Spatial features

In [66]:
df_no_spatial = df_cont_cat_text
df_no_spatial = df_no_spatial.drop(columns=["neighbourhood_cleansed","zipcode","latitude","longitude"])
df_no_spatial.head()

,log_price,host_listings_count,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,number_of_reviews,number_of_reviews_ltm,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,property_type,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,private,shared,flexible,moderate,summary_SVD1,summary_SVD2,summary_SVD3,space_SVD1,space_SVD2,space_SVD3,description_SVD1,description_SVD2,description_SVD3,neighborhood_overview_SVD1,neighborhood_overview_SVD2,neighborhood_overview_SVD3,access_SVD1,access_SVD2,access_SVD3,interaction_SVD1,interaction_SVD2,interaction_SVD3,house_rules_SVD1,house_rules_SVD2,house_rules_SVD3,host_about_SVD1,host_about_SVD2,host_about_SVD3
0,6.493754,1.0,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,49,7,0,0,0.610000,21,1,0,0,0,0,0,2663.663320,0,0,0,1,-3.617314e-02,2.243312e-02,-4.086990e-02,0.001492,-0.124890,0.038315,0.010927,-0.146725,-0.096208,-0.010653,-0.003074,-0.102751,-0.038241,-0.165265,0.139044,0.010833,-0.010946,-0.003911,0.150103,-0.020829,0.094639,-1.661607e-01,-1.274255e-02,-4.633390e-02
1,7.652071,5.0,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,2,0,0,0,0.020000,3,0,0,0,1,0,0,1459.786779,0,0,0,0,-5.004628e-02,-3.579589e-02,3.588734e-02,0.022125,0.019245,0.034231,0.005448,-0.021422,-0.029890,0.089120,-0.004582,0.040303,-0.082266,-0.157155,0.064531,0.008448,-0.048546,-0.077724,-0.021170,-0.010612,0.142739,1.258846e-01,1.352890e-02,3.054207e-02
2,7.624619,12.0,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,27,2,0,0,0.370000,25,1,0,0,1,0,0,3612.146587,0,0,0,0,6.196324e-02,6.545631e-03,-1.251741e-01,0.058922,-0.003018,-0.087462,-0.051035,0.063836,-0.106632,0.056761,0.018276,0.027745,0.090246,-0.084449,0.026858,-0.062756,-0.004105,0.048072,-0.002762,0.029302,0.165877,-4.881418e-02,2.009630e-03,3.447136e-02
3,7.198184,5.0,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,5,0,4,0,0.060000,1,0,0,0,1,0,0,3260.343187,1,0,0,0,-1.029555e-01,-5.844210e-02,3.283490e-02,0.028287,0.112263,-0.031700,-0.006912,-0.017670,-0.009801,-0.081795,-0.042419,-0.101334,0.018954,-0.039953,0.004325,-0.085090,-0.053575,0.009867,-0.036506,-0.018924,-0.245281,1.268197e-01,-8.067963e-02,3.203286e-03
4,6.329721,1.0,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,0,0,0,0,0.919543,1,1,0,0,1,0,0,512.116431,0,0,0,0,-2.054624e-16,-8.809054e-17,2.373795e-15,-0.051308,-0.073710,-0.068863,0.102251,-0.046986,0.035174,0.016118,0.041624,-0.007335,-0.063371,0.012052,0.032089,-0.092871,0.015986,0.066478,0.078126,-0.018296,0.068100,-4.288458e-17,-9.670931e-16,-1.121728e-15

## Experiment 2.3 - Normal features (incl. spatial)

In [67]:
df_normal = df_cont_cat_text
df_normal.head()

,log_price,host_listings_count,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,latitude,longitude,number_of_reviews,number_of_reviews_ltm,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,neighbourhood_cleansed,zipcode,property_type,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,private,shared,flexible,moderate,summary_SVD1,summary_SVD2,summary_SVD3,space_SVD1,space_SVD2,space_SVD3,description_SVD1,description_SVD2,description_SVD3,neighborhood_overview_SVD1,neighborhood_overview_SVD2,neighborhood_overview_SVD3,access_SVD1,access_SVD2,access_SVD3,interaction_SVD1,interaction_SVD2,interaction_SVD3,house_rules_SVD1,house_rules_SVD2,house_rules_SVD3,host_about_SVD1,host_about_SVD2,host_about_SVD3
0,6.493754,1.0,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,-33.94739,18.47600,49,7,0,0,0.610000,58,62,21,1,0,0,0,0,0,2663.663320,0,0,0,1,-3.617314e-02,2.243312e-02,-4.086990e-02,0.001492,-0.124890,0.038315,0.010927,-0.146725,-0.096208,-0.010653,-0.003074,-0.102751,-0.038241,-0.165265,0.139044,0.010833,-0.010946,-0.003911,0.150103,-0.020829,0.094639,-1.661607e-01,-1.274255e-02,-4.633390e-02
1,7.652071,5.0,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,-33.90771,18.40535,2,0,0,0,0.020000,17,125,3,0,0,0,1,0,0,1459.786779,0,0,0,0,-5.004628e-02,-3.579589e-02,3.588734e-02,0.022125,0.019245,0.034231,0.005448,-0.021422,-0.029890,0.089120,-0.004582,0.040303,-0.082266,-0.157155,0.064531,0.008448,-0.048546,-0.077724,-0.021170,-0.010612,0.142739,1.258846e-01,1.352890e-02,3.054207e-02
2,7.624619,12.0,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,-33.80114,18.46180,27,2,0,0,0.370000,30,31,25,1,0,0,1,0,0,3612.146587,0,0,0,0,6.196324e-02,6.545631e-03,-1.251741e-01,0.058922,-0.003018,-0.087462,-0.051035,0.063836,-0.106632,0.056761,0.018276,0.027745,0.090246,-0.084449,0.026858,-0.062756,-0.004105,0.048072,-0.002762,0.029302,0.165877,-4.881418e-02,2.009630e-03,3.447136e-02
3,7.198184,5.0,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,-33.85878,18.48970,5,0,4,0,0.060000,41,31,1,0,0,0,1,0,0,3260.343187,1,0,0,0,-1.029555e-01,-5.844210e-02,3.283490e-02,0.028287,0.112263,-0.031700,-0.006912,-0.017670,-0.009801,-0.081795,-0.042419,-0.101334,0.018954,-0.039953,0.004325,-0.085090,-0.053575,0.009867,-0.036506,-0.018924,-0.245281,1.268197e-01,-8.067963e-02,3.203286e-03
4,6.329721,1.0,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,-34.11124,18.82349,0,0,0,0,0.919543,86,16,1,1,0,0,1,0,0,512.116431,0,0,0,0,-2.054624e-16,-8.809054e-17,2.373795e-15,-0.051308,-0.073710,-0.068863,0.102251,-0.046986,0.035174,0.016118,0.041624,-0.007335,-0.063371,0.012052,0.032089,-0.092871,0.015986,0.066478,0.078126,-0.018296,0.068100,-4.288458e-17,-9.670931e-16,-1.121728e-15

## Experiment 2.4 - All features (incl. spatial and enharnced spatial)

In [68]:
df_spatial_all =  pd.concat([df_no_spatial,df_spatial_only], axis=1)
df_spatial_all = df_spatial_all.loc[:,~df_spatial_all.columns.duplicated()]
df_spatial_all.head()

,log_price,host_listings_count,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,maximum_minimum_nights,review_scores_rating,review_scores_location,number_of_reviews,number_of_reviews_ltm,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,property_type,entire,luxury_moderate,luxury_super_strict_95,strict_14_with_grace_period,super_strict_30,super_strict_60,amenity_scores,private,shared,flexible,moderate,summary_SVD1,summary_SVD2,summary_SVD3,space_SVD1,space_SVD2,space_SVD3,description_SVD1,description_SVD2,description_SVD3,neighborhood_overview_SVD1,neighborhood_overview_SVD2,neighborhood_overview_SVD3,access_SVD1,access_SVD2,access_SVD3,interaction_SVD1,interaction_SVD2,interaction_SVD3,house_rules_SVD1,house_rules_SVD2,house_rules_SVD3,host_about_SVD1,host_about_SVD2,host_about_SVD3,ward,Low income,Middle-Low Income,Medium Income,High Income,Exceedingly High Income,listing_count,table_mountain_dist,beach_dist,Promenade,Wine,zipcode,latitude,longitude
0,6.493754,1.0,2,1.0,1.0,1.0,2656.082216,211.000000,2,3,97.000000,9.000000,49,7,0,0,0.610000,21,1,0,0,0,0,0,2663.663320,0,0,0,1,-3.617314e-02,2.243312e-02,-4.086990e-02,0.001492,-0.124890,0.038315,0.010927,-0.146725,-0.096208,-0.010653,-0.003074,-0.102751,-0.038241,-0.165265,0.139044,0.010833,-0.010946,-0.003911,0.150103,-0.020829,0.094639,-1.661607e-01,-1.274255e-02,-4.633390e-02,57.0,0,0,1,0,0,819.0,5992.238320,8846.454557,8559.224147,0.0,62,-33.94739,18.47600
1,7.652071,5.0,2,1.0,1.0,1.0,0.000000,0.000000,2,3,100.000000,10.000000,2,0,0,0,0.020000,3,0,0,0,1,0,0,1459.786779,0,0,0,0,-5.004628e-02,-3.579589e-02,3.588734e-02,0.022125,0.019245,0.034231,0.005448,-0.021422,-0.029890,0.089120,-0.004582,0.040303,-0.082266,-0.157155,0.064531,0.008448,-0.048546,-0.077724,-0.021170,-0.010612,0.142739,1.258846e-01,1.352890e-02,3.054207e-02,115.0,0,0,1,0,0,4307.0,4481.215598,1010.942474,840.630176,1.0,125,-33.90771,18.40535
2,7.624619,12.0,6,3.0,3.0,4.0,2500.000000,850.000000,6,2,97.000000,10.000000,27,2,0,0,0.370000,25,1,0,0,1,0,0,3612.146587,0,0,0,0,6.196324e-02,6.545631e-03,-1.251741e-01,0.058922,-0.003018,-0.087462,-0.051035,0.063836,-0.106632,0.056761,0.018276,0.027745,0.090246,-0.084449,0.026858,-0.062756,-0.004105,0.048072,-0.002762,0.029302,0.165877,-4.881418e-02,2.009630e-03,3.447136e-02,23.0,0,0,0,1,0,1330.0,17212.514919,646.514699,12342.796409,0.0,31,-33.80114,18.46180
3,7.198184,5.0,2,1.5,1.0,2.0,2656.082216,322.727352,2,5,100.000000,10.000000,5,0,4,0,0.060000,1,0,0,0,1,0,0,3260.343187,1,0,0,0,-1.029555e-01,-5.844210e-02,3.283490e-02,0.028287,0.112263,-0.031700,-0.006912,-0.017670,-0.009801,-0.081795,-0.042419,-0.101334,0.018954,-0.039953,0.004325,-0.085090,-0.053575,0.009867,-0.036506,-0.018924,-0.245281,1.268197e-01,-8.067963e-02,3.203286e-03,4.0,0,1,0,0,0,334.0,12759.126712,4387.900693,9304.817930,0.0,31,-33.85878,18.48970
4,6.329721,1.0,2,1.0,1.0,1.0,2656.082216,150.000000,2,2,94.834741,9.719734,0,0,0,0,0.919543,1,1,0,0,1,0,0,512.116431,0,0,0,0,-2.054624e-16,-8.809054e-17,2.373795e-15,-0.051308,-0.073710,-0.068863,0.102251,-0.046986,0.035174,0.016118,0.041624,-0.007335,-0.063371,0.012052,0.032089,-0.092871,0.015986,0.066478,0.078126,-0.018296,0.068100,-4.288458e-17,-9.670931e-16,-1.121728e-15,83.0,0,1,0,0,0,271.0,42818.200051,154.279498,45338.822717,0.0,16,-34.11124,18.82349

## Write all datasets to file

In [69]:
df_continuous.to_csv("../6-Experimental Data - continuous.csv", index=False) 
df_cat.to_csv("../6-Experimental Data - categorical.csv", index=False) 
df_text.to_csv("../6-Experimental Data - text.csv", index=False) 
df_cont_cat.to_csv("../6-Experimental Data - cont_cat.csv", index=False) 
df_cont_cat_text.to_csv("../6-Experimental Data - cont_cat_text.csv", index=False) 


df_spatial_only.to_csv("../6-Experimental Data - spatial 1 - only spatial.csv", index=False) 
df_no_spatial.to_csv("../6-Experimental Data - spatial 2 - no spatial.csv", index=False) 
df_normal.to_csv("../6-Experimental Data - spatial 3 - normal spatial.csv", index=False) 
df_spatial_all.to_csv("../6-Experimental Data - spatial 4 - normal+enh spatial.csv", index=False)